#file: noinspection undefined
spring:
  application:
    name: authorization-server
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${MYSQL_DATABASE}
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@localhost:8761/eureka/

server:
  port: ${CONTAINER_PORT:8081}
  error:
    whitelabel:
      enabled: false

ui:
  app:
    url: ${UI_APP_URL}

keys:
  private: ${PRIVATE_KEY}
  public: ${PUBLIC_KEY}

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE

